# Generated by Django 2.2.4 on 2019-08-15 12:49

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190815_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='avatars/default.png', upload_to=users.models.get_avatar_path),
        ),
    ]
