# Generated by Django 2.2.4 on 2019-08-23 10:15

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190815_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_preview',
            field=models.ImageField(null=True, upload_to=users.models.get_avatar_preview_path),
        ),
    ]
