# Generated by Django 2.2.4 on 2019-08-23 10:58

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_avatar_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='avatars/default.png', null=True, upload_to=users.models.get_avatar_path),
        ),
    ]
