# Generated by Django 2.2.4 on 2019-08-23 10:59

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190823_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', upload_to=users.models.get_avatar_path),
        ),
    ]
