# Generated by Django 2.2.4 on 2019-08-22 11:08

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190815_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='logo',
            field=models.ImageField(null=True, upload_to=blog.models.get_logo_path),
        ),
        migrations.AddField(
            model_name='article',
            name='logo_preview',
            field=models.ImageField(default='articles/logo/<django.db.models.fields.files.ImageField>', upload_to=blog.models.get_logo_preview_path),
        ),
    ]
