# Generated by Django 2.2.4 on 2019-08-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190822_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('prog', 'Programming'), ('robo', 'Robotics'), ('math', 'Mathematics'), ('cs', 'Computer Science'), ('bc', 'Blockchain'), ('iot', 'Internet Of Things'), ('ml', 'Machine Learning'), ('hard', 'Hardware'), ('do', 'DevOps')], max_length=4),
        ),
    ]
