# Generated by Django 2.2.4 on 2019-08-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article_annotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='annotation',
            field=models.TextField(default='Lorem ipsum', max_length=200),
        ),
    ]
